<?php

use Illuminate\Database\Seeder;

class RequisitoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110001',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110002',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110003',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110004',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110005',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110006',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110007',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110008',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110009',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110010',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110011',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110012',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);
      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110013',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110014',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110015',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110016',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110017',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110018',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110019',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110020',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110021',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110022',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110023',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110024',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);
      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110025',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110026',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110027',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110028',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110029',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110030',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110031',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110032',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110033',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110034',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110035',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110036',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110037',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);
      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110038',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110039',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110040',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110041',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110042',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110043',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110044',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110045',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110046',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110047',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110048',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);

      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110049',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);
      DB::table('Requisitos')->insert([
          'Clave_A'=>'1900110050',
          'Requisito_A'=>'Si',
          'Requisito_B'=>'Si',
          'Requisito_C'=>'Si',
          'Requisito_D'=>'Si',
          'Requisito_E'=>'Si',
          'Requisito_F'=>'Si',
          'Requisito_G'=>'Si',
          'Requisito_H'=>'Si'
      ]);
    }

}
